Added tests
ms1-learner/python-05-jp pull request #3
Opened 2023-09-08 07:05 UTC by dancer-yuma

# What I did

- added tests
- added required.yml

2023-09-08 07:06 UTC, dancer-yuma reviewed
Self review

2023-09-08 07:06 UTC, dancer-yuma commented on 01_debugging/03_stackoverflow/stackoverflow.txt
> +https://stackoverflow.com/questions/tagged/python?tab=Newest (英語)を開き、
Note
Small fix to make the URL work.

2023-09-11 03:16 UTC, xvarc-wp requested changes
Nice work @dancer-yuma , raised one issue and requested change.

2023-09-11 03:16 UTC, xvarc-wp commented on 02_classes-objects-methods/04_classy_shapes/test_classy_shapes.py
Hi @dancer-yuma , one of the things I mentioned last time was the risk of expecting precise values, especially if they are integers. You have used exact values for the expected outputs of circle calculations. This can sometimes lead to precision issues, especially with floating-point arithmetic. It's often a good idea to use a small tolerance when comparing float values, for example using pytest.approx() or by specifying a range:

I might do it something like this: 
assert instance.calculate_area() == pytest.approx(expected_output)

2023-09-11 03:16 UTC, xvarc-wp commented on 02_classes-objects-methods/04_classy_shapes/test_classy_shapes.py
I have the same concern with the expected output here.

2023-09-11 04:04 UTC, dancer-yuma commented on 02_classes-objects-methods/04_classy_shapes/test_classy_shapes.py
You're right. I was not very concerned because the output will be multiplied, but let me fix them!

2023-09-11 04:08 UTC, dancer-yuma commented on 02_classes-objects-methods/04_classy_shapes/test_classy_shapes.py
Fixed in [4b17265](https://github.com/ms1-learner/python-05-jp/pull/3/commits/4b17265952ba88847b7b3ed630fef5f51e737281).

2023-09-11 04:08 UTC, dancer-yuma commented on 02_classes-objects-methods/04_classy_shapes/test_classy_shapes.py
Fixed in [4b17265](https://github.com/ms1-learner/python-05-jp/pull/3/commits/4b17265952ba88847b7b3ed630fef5f51e737281).

2023-09-11 04:08 UTC, dancer-yuma commented
@xvarc-wp 
Please review again! Added [4b17265](https://github.com/ms1-learner/python-05-jp/pull/3/commits/4b17265952ba88847b7b3ed630fef5f51e737281) to fix based on your comments.

2023-09-11 06:35 UTC, xvarc-wp approved these changes

2023-09-11 06:35 UTC, merged